FROM nvidia/cuda:12.1.1-devel-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y python3 python3-pip git && rm -rf /var/lib/apt/lists/*
RUN pip3 install --upgrade pip
COPY requirements.quantize.txt ./requirements.txt
RUN pip3 install -r requirements.txt


COPY scripts/quantize.py /app/quantize.py

CMD ["python3", "quantize.py"]
