FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install numpy==1.26.4 pandas==2.3.3 scipy==1.10.1 triton==3.5.0 cupy-cuda12x==13.1.0
RUN pip install -r requirements.txt

CMD ["python", "-c", "import numpy; print('numpy version:', numpy.__version__)"]
